---
strategy: polling
no_screen_padding: 
dark_mode: 
static_data: 
polling_verb: 
polling_url: https://trmnl-dsn.netlify.app/dsn.json
polling_headers: ''
id: 9540
name: NASA Deep Space Network
refresh_interval: 60
